### PR TITLE
Coq 8.16 compatibility

### PR DESCRIPTION
**Pull request by haansn08**
This PR makes the changes necessary to build the project with Coq 8.16 without warnings:

- I used https://github.com/uds-psl/coq-library-undecidability/tree/coq-8.16 for the source of the `Complexity` library. The submodule referenced `fakusb/coq-library-undecidability` does not yet have this branch.
- GitHub does not allow PRs to create new branches, so the base ref of this branch is `coq-8.15`.

### CODE REVIEW

**Comment by haansn08** [comment]
This commit https://github.com/uds-psl/coq-library-undecidability/commit/5a0792b593e2fd7d74c35a021e971cf3122a6ded removes a lot `coq-library-complexity` is using.

**Comment by haansn08** [comment]
@fakusb Is there a possibility this gets merged on a `coq-8.16` branch?

**Comment by yforster** [comment]
I can create an 8.16 branch and would be interested in creating an `opam` package with the current content of the library. The CI currently seems to be failing though. Is that expected? Is it a real compilation problem, or just a CI problem? I'm happy to help debug CI problems.

**Comment by haansn08** [comment]
@fakusb Thank you for your reply. If you should create a `coq-8.16` branch I will change the target branch of this PR.

For compilation to succeed, a compiled version of `coq-library-undecidability` from the `coq-8.16` branch must be in the path. For reference, right now this refers to [this commit](https://github.com/uds-psl/coq-library-undecidability/tree/2eeb588b2eecd8f0ee651d91c1fd2552b4e15014).

**Comment by yforster** [comment]
I used your branch as base of a new `coq-8.16` branch and CI. It's working, thanks a lot :)

**Pull request closed without merging**
